default:
  image: docker:stable
  services:
    - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

.build:
  stage: build
  script:
    - cd "./${BUILD_DIR}"
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - >
      docker image pull "${CI_REGISTRY_IMAGE}-${BUILD_NAME}:latest" ||
      true
    - >
      docker build
      --cache-from "${CI_REGISTRY_IMAGE}-${BUILD_NAME}:latest"
      -t "${CI_REGISTRY_IMAGE}-${BUILD_NAME}:latest"
      .
    - docker push "${CI_REGISTRY_IMAGE}-${BUILD_NAME}:latest"

alpine-curl:
  extends: .build
  variables:
    BUILD_DIR: "Alpine-Curl"
    BUILD_NAME: "alpine-curl"
